# --- !Ups

create table "roles" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar
);

create table "permissions" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "obj" varchar not null,
  "action" varchar not null
);

create table "rolePermissions" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "permissionId" int,
  "roleId" int
);

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "firstName" varchar not null,
  "lastName" varchar not null,
  "displayName" varchar,
  "email" varchar not null,
  "dateOfBirth" varchar not null,
  "gender" varchar not null,
  "phone" varchar,
  "address" varchar,
  "picture" varchar,
  "login" varchar not null,
  "password" varchar not null,
  "roleId" int
);

alter table "users" add constraint fk_roleid foreign key ( "roleId" ) references "roles" ("id");
alter table "rolePermissions" add constraint fk_rolepermissionId foreign key ( "roleId" ) references "roles" ("id");
alter table "rolePermissions" add constraint fk_rolesroled foreign key ( "permissionId" ) references "permissions" ("id");

# --- !Downs

drop table "rolePermissions" if exists;
drop table "users" if exists;
drop table "roles" if exists;
drop table "permissions" if exists;