# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "firstName" varchar not null,
  "lastName" varchar not null,
  "email" varchar not null,
  "dateOfBirth" varchar not null,
  "gender" varchar not null,
);

# --- !Downs

drop table "users" if exists;