# --- !Ups

create table "roles" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null
);

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "firstName" varchar not null,
  "lastName" varchar not null,
  "email" varchar not null,
  "dateOfBirth" varchar not null,
  "gender" varchar not null,
  "roleId" int,
);

alter table "users" add constraint fk_roleid foreign key ( "roleId" ) references "roles" ("id")

# --- !Downs

drop table "users" if exists;
drop table "roles" if exists;